# Generated by Django 4.2.6 on 2023-10-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0002_monster_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
