# Generated by Django 4.2.6 on 2023-10-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_monster_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='img_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
